# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {Synth 8-567}  -suppress 
create_project -in_memory -part xa7a100tcsg324-1I

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/iyuge2/project_yuge/project_yuge.cache/wt [current_project]
set_property parent.project_path D:/iyuge2/project_yuge/project_yuge.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/iyuge2/project_yuge/project_yuge.srcs/sources_1/new/segTime.v
  D:/iyuge2/project_yuge/project_yuge.srcs/sources_1/new/SevenSeg.v
  D:/iyuge2/project_yuge/project_yuge.srcs/sources_1/new/BitsToNum.v
  D:/iyuge2/project_yuge/project_yuge.srcs/sources_1/new/PRINT.v
  D:/iyuge2/project_yuge/project_yuge.srcs/sources_1/new/ChangeState.v
  D:/iyuge2/project_yuge/project_yuge.srcs/sources_1/new/DLCK_1s.v
  D:/iyuge2/project_yuge/project_yuge.srcs/sources_1/new/Main.v
}
read_xdc D:/iyuge2/project_yuge/project_yuge.srcs/constrs_1/new/ConMan.xdc
set_property used_in_implementation false [get_files D:/iyuge2/project_yuge/project_yuge.srcs/constrs_1/new/ConMan.xdc]

synth_design -top Main -part xa7a100tcsg324-1I
write_checkpoint -noxdef Main.dcp
catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
