# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7a100tcsg324-1I

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/project_yu1433/project_yu1433.cache/wt [current_project]
set_property parent.project_path D:/project_yu1433/project_yu1433.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/Count.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/SevenSeg.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/segTime.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/RING.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/DCLK_1.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/DCLK_05.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/CLOCK_S.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/CLOCK_M.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/CLOCK_H.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/PRINT.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/Clock_loud.v
  D:/project_yu1433/project_yu1433.srcs/sources_1/new/Main.v
}
read_xdc D:/project_yu1433/project_yu1433.srcs/constrs_1/new/ConMain.xdc
set_property used_in_implementation false [get_files D:/project_yu1433/project_yu1433.srcs/constrs_1/new/ConMain.xdc]

synth_design -top Main -part xa7a100tcsg324-1I
write_checkpoint -noxdef Main.dcp
catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
