# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xa7a100tcsg324-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.cache/wt [current_project]
set_property parent.project_path /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.srcs/sources_1/new/CLOCK_H.v
  /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.srcs/sources_1/new/CLOCK_M.v
  /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.srcs/sources_1/new/CLOCK_S.v
  /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.srcs/sources_1/new/Count.v
  /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.srcs/sources_1/new/RING.v
  /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.srcs/sources_1/new/Main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.srcs/constrs_1/new/ConMain.xdc
set_property used_in_implementation false [get_files /home/iyuge2/git/hust-mylab/NumLogic/EleClock/project_yu1433.srcs/constrs_1/new/ConMain.xdc]


synth_design -top Main -part xa7a100tcsg324-1I


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
